
all: distilbert_albert.pdf lora_qlora.pdf

distilbert_albert.pdf: distilbert_albert_advanced.tex
	pdflatex -interaction=nonstopmode $<

lora_qlora.pdf: lora_qlora_advanced.tex
	pdflatex -interaction=nonstopmode $<
